project_id = "hywqedthwvuiftmfmkjs"

[functions.setup-admin]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.check-email-exists]
verify_jwt = false

[functions.send-reset-code]
verify_jwt = false

[functions.verify-reset-code]
verify_jwt = false

[functions.expire-withdrawals]
verify_jwt = false

[functions.ban-user]
verify_jwt = false