import { useState, useEffect } from 'react';

interface CountryData {
  country: string;
  countryCode: string;
  isLoading: boolean;
  error: string | null;
}

const countries = [
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', phoneDigits: 9 },
  { code: 'AL', name: 'Albania', dialCode: '+355', phoneDigits: 9 },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', phoneDigits: 9 },
  { code: 'AD', name: 'Andorra', dialCode: '+376', phoneDigits: 6 },
  { code: 'AO', name: 'Angola', dialCode: '+244', phoneDigits: 9 },
  { code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1268', phoneDigits: 7 },
  { code: 'AR', name: 'Argentina', dialCode: '+54', phoneDigits: 10 },
  { code: 'AM', name: 'Armenia', dialCode: '+374', phoneDigits: 8 },
  { code: 'AU', name: 'Australia', dialCode: '+61', phoneDigits: 9 },
  { code: 'AT', name: 'Austria', dialCode: '+43', phoneDigits: 10 },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', phoneDigits: 9 },
  { code: 'BS', name: 'Bahamas', dialCode: '+1242', phoneDigits: 7 },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', phoneDigits: 8 },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', phoneDigits: 10 },
  { code: 'BB', name: 'Barbados', dialCode: '+1246', phoneDigits: 7 },
  { code: 'BY', name: 'Belarus', dialCode: '+375', phoneDigits: 9 },
  { code: 'BE', name: 'Belgium', dialCode: '+32', phoneDigits: 9 },
  { code: 'BZ', name: 'Belize', dialCode: '+501', phoneDigits: 7 },
  { code: 'BJ', name: 'Benin', dialCode: '+229', phoneDigits: 8 },
  { code: 'BT', name: 'Bhutan', dialCode: '+975', phoneDigits: 8 },
  { code: 'BO', name: 'Bolivia', dialCode: '+591', phoneDigits: 8 },
  { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', phoneDigits: 8 },
  { code: 'BW', name: 'Botswana', dialCode: '+267', phoneDigits: 8 },
  { code: 'BR', name: 'Brazil', dialCode: '+55', phoneDigits: 11 },
  { code: 'BN', name: 'Brunei', dialCode: '+673', phoneDigits: 7 },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359', phoneDigits: 9 },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', phoneDigits: 8 },
  { code: 'BI', name: 'Burundi', dialCode: '+257', phoneDigits: 8 },
  { code: 'KH', name: 'Cambodia', dialCode: '+855', phoneDigits: 9 },
  { code: 'CM', name: 'Cameroon', dialCode: '+237', phoneDigits: 9 },
  { code: 'CA', name: 'Canada', dialCode: '+1', phoneDigits: 10 },
  { code: 'CV', name: 'Cape Verde', dialCode: '+238', phoneDigits: 7 },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236', phoneDigits: 8 },
  { code: 'TD', name: 'Chad', dialCode: '+235', phoneDigits: 8 },
  { code: 'CL', name: 'Chile', dialCode: '+56', phoneDigits: 9 },
  { code: 'CN', name: 'China', dialCode: '+86', phoneDigits: 11 },
  { code: 'CO', name: 'Colombia', dialCode: '+57', phoneDigits: 10 },
  { code: 'KM', name: 'Comoros', dialCode: '+269', phoneDigits: 7 },
  { code: 'CG', name: 'Congo', dialCode: '+242', phoneDigits: 9 },
  { code: 'CD', name: 'DR Congo', dialCode: '+243', phoneDigits: 9 },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', phoneDigits: 8 },
  { code: 'CI', name: "Côte d'Ivoire", dialCode: '+225', phoneDigits: 10 },
  { code: 'HR', name: 'Croatia', dialCode: '+385', phoneDigits: 9 },
  { code: 'CU', name: 'Cuba', dialCode: '+53', phoneDigits: 8 },
  { code: 'CY', name: 'Cyprus', dialCode: '+357', phoneDigits: 8 },
  { code: 'CZ', name: 'Czech Republic', dialCode: '+420', phoneDigits: 9 },
  { code: 'DK', name: 'Denmark', dialCode: '+45', phoneDigits: 8 },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253', phoneDigits: 8 },
  { code: 'DM', name: 'Dominica', dialCode: '+1767', phoneDigits: 7 },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1809', phoneDigits: 7 },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', phoneDigits: 9 },
  { code: 'EG', name: 'Egypt', dialCode: '+20', phoneDigits: 10 },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', phoneDigits: 8 },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', phoneDigits: 9 },
  { code: 'ER', name: 'Eritrea', dialCode: '+291', phoneDigits: 7 },
  { code: 'EE', name: 'Estonia', dialCode: '+372', phoneDigits: 8 },
  { code: 'SZ', name: 'Eswatini', dialCode: '+268', phoneDigits: 8 },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', phoneDigits: 9 },
  { code: 'FJ', name: 'Fiji', dialCode: '+679', phoneDigits: 7 },
  { code: 'FI', name: 'Finland', dialCode: '+358', phoneDigits: 9 },
  { code: 'FR', name: 'France', dialCode: '+33', phoneDigits: 9 },
  { code: 'GA', name: 'Gabon', dialCode: '+241', phoneDigits: 8 },
  { code: 'GM', name: 'Gambia', dialCode: '+220', phoneDigits: 7 },
  { code: 'GE', name: 'Georgia', dialCode: '+995', phoneDigits: 9 },
  { code: 'DE', name: 'Germany', dialCode: '+49', phoneDigits: 11 },
  { code: 'GH', name: 'Ghana', dialCode: '+233', phoneDigits: 9 },
  { code: 'GR', name: 'Greece', dialCode: '+30', phoneDigits: 10 },
  { code: 'GD', name: 'Grenada', dialCode: '+1473', phoneDigits: 7 },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', phoneDigits: 8 },
  { code: 'GN', name: 'Guinea', dialCode: '+224', phoneDigits: 9 },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', phoneDigits: 7 },
  { code: 'GY', name: 'Guyana', dialCode: '+592', phoneDigits: 7 },
  { code: 'HT', name: 'Haiti', dialCode: '+509', phoneDigits: 8 },
  { code: 'HN', name: 'Honduras', dialCode: '+504', phoneDigits: 8 },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', phoneDigits: 8 },
  { code: 'HU', name: 'Hungary', dialCode: '+36', phoneDigits: 9 },
  { code: 'IS', name: 'Iceland', dialCode: '+354', phoneDigits: 7 },
  { code: 'IN', name: 'India', dialCode: '+91', phoneDigits: 10 },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', phoneDigits: 11 },
  { code: 'IR', name: 'Iran', dialCode: '+98', phoneDigits: 10 },
  { code: 'IQ', name: 'Iraq', dialCode: '+964', phoneDigits: 10 },
  { code: 'IE', name: 'Ireland', dialCode: '+353', phoneDigits: 9 },
  { code: 'IL', name: 'Israel', dialCode: '+972', phoneDigits: 9 },
  { code: 'IT', name: 'Italy', dialCode: '+39', phoneDigits: 10 },
  { code: 'JM', name: 'Jamaica', dialCode: '+1876', phoneDigits: 7 },
  { code: 'JP', name: 'Japan', dialCode: '+81', phoneDigits: 10 },
  { code: 'JO', name: 'Jordan', dialCode: '+962', phoneDigits: 9 },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', phoneDigits: 10 },
  { code: 'KE', name: 'Kenya', dialCode: '+254', phoneDigits: 9 },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', phoneDigits: 8 },
  { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', phoneDigits: 9 },
  { code: 'LA', name: 'Laos', dialCode: '+856', phoneDigits: 9 },
  { code: 'LV', name: 'Latvia', dialCode: '+371', phoneDigits: 8 },
  { code: 'LB', name: 'Lebanon', dialCode: '+961', phoneDigits: 8 },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', phoneDigits: 8 },
  { code: 'LR', name: 'Liberia', dialCode: '+231', phoneDigits: 8 },
  { code: 'LY', name: 'Libya', dialCode: '+218', phoneDigits: 9 },
  { code: 'LI', name: 'Liechtenstein', dialCode: '+423', phoneDigits: 7 },
  { code: 'LT', name: 'Lithuania', dialCode: '+370', phoneDigits: 8 },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', phoneDigits: 9 },
  { code: 'MO', name: 'Macau', dialCode: '+853', phoneDigits: 8 },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', phoneDigits: 9 },
  { code: 'MW', name: 'Malawi', dialCode: '+265', phoneDigits: 9 },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', phoneDigits: 9 },
  { code: 'MV', name: 'Maldives', dialCode: '+960', phoneDigits: 7 },
  { code: 'ML', name: 'Mali', dialCode: '+223', phoneDigits: 8 },
  { code: 'MT', name: 'Malta', dialCode: '+356', phoneDigits: 8 },
  { code: 'MR', name: 'Mauritania', dialCode: '+222', phoneDigits: 8 },
  { code: 'MU', name: 'Mauritius', dialCode: '+230', phoneDigits: 8 },
  { code: 'MX', name: 'Mexico', dialCode: '+52', phoneDigits: 10 },
  { code: 'MD', name: 'Moldova', dialCode: '+373', phoneDigits: 8 },
  { code: 'MC', name: 'Monaco', dialCode: '+377', phoneDigits: 8 },
  { code: 'MN', name: 'Mongolia', dialCode: '+976', phoneDigits: 8 },
  { code: 'ME', name: 'Montenegro', dialCode: '+382', phoneDigits: 8 },
  { code: 'MA', name: 'Morocco', dialCode: '+212', phoneDigits: 9 },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', phoneDigits: 9 },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', phoneDigits: 9 },
  { code: 'NA', name: 'Namibia', dialCode: '+264', phoneDigits: 9 },
  { code: 'NP', name: 'Nepal', dialCode: '+977', phoneDigits: 10 },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', phoneDigits: 9 },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', phoneDigits: 9 },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', phoneDigits: 8 },
  { code: 'NE', name: 'Niger', dialCode: '+227', phoneDigits: 8 },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', phoneDigits: 10 },
  { code: 'KP', name: 'North Korea', dialCode: '+850', phoneDigits: 10 },
  { code: 'MK', name: 'North Macedonia', dialCode: '+389', phoneDigits: 8 },
  { code: 'NO', name: 'Norway', dialCode: '+47', phoneDigits: 8 },
  { code: 'OM', name: 'Oman', dialCode: '+968', phoneDigits: 8 },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', phoneDigits: 10 },
  { code: 'PS', name: 'Palestine', dialCode: '+970', phoneDigits: 9 },
  { code: 'PA', name: 'Panama', dialCode: '+507', phoneDigits: 8 },
  { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', phoneDigits: 8 },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', phoneDigits: 9 },
  { code: 'PE', name: 'Peru', dialCode: '+51', phoneDigits: 9 },
  { code: 'PH', name: 'Philippines', dialCode: '+63', phoneDigits: 10 },
  { code: 'PL', name: 'Poland', dialCode: '+48', phoneDigits: 9 },
  { code: 'PT', name: 'Portugal', dialCode: '+351', phoneDigits: 9 },
  { code: 'QA', name: 'Qatar', dialCode: '+974', phoneDigits: 8 },
  { code: 'RO', name: 'Romania', dialCode: '+40', phoneDigits: 9 },
  { code: 'RU', name: 'Russia', dialCode: '+7', phoneDigits: 10 },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', phoneDigits: 9 },
  { code: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1869', phoneDigits: 7 },
  { code: 'LC', name: 'Saint Lucia', dialCode: '+1758', phoneDigits: 7 },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '+1784', phoneDigits: 7 },
  { code: 'WS', name: 'Samoa', dialCode: '+685', phoneDigits: 7 },
  { code: 'SM', name: 'San Marino', dialCode: '+378', phoneDigits: 10 },
  { code: 'ST', name: 'São Tomé and Príncipe', dialCode: '+239', phoneDigits: 7 },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', phoneDigits: 9 },
  { code: 'SN', name: 'Senegal', dialCode: '+221', phoneDigits: 9 },
  { code: 'RS', name: 'Serbia', dialCode: '+381', phoneDigits: 9 },
  { code: 'SC', name: 'Seychelles', dialCode: '+248', phoneDigits: 7 },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', phoneDigits: 8 },
  { code: 'SG', name: 'Singapore', dialCode: '+65', phoneDigits: 8 },
  { code: 'SK', name: 'Slovakia', dialCode: '+421', phoneDigits: 9 },
  { code: 'SI', name: 'Slovenia', dialCode: '+386', phoneDigits: 8 },
  { code: 'SB', name: 'Solomon Islands', dialCode: '+677', phoneDigits: 7 },
  { code: 'SO', name: 'Somalia', dialCode: '+252', phoneDigits: 8 },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', phoneDigits: 9 },
  { code: 'KR', name: 'South Korea', dialCode: '+82', phoneDigits: 10 },
  { code: 'SS', name: 'South Sudan', dialCode: '+211', phoneDigits: 9 },
  { code: 'ES', name: 'Spain', dialCode: '+34', phoneDigits: 9 },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', phoneDigits: 9 },
  { code: 'SD', name: 'Sudan', dialCode: '+249', phoneDigits: 9 },
  { code: 'SR', name: 'Suriname', dialCode: '+597', phoneDigits: 7 },
  { code: 'SE', name: 'Sweden', dialCode: '+46', phoneDigits: 9 },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', phoneDigits: 9 },
  { code: 'SY', name: 'Syria', dialCode: '+963', phoneDigits: 9 },
  { code: 'TW', name: 'Taiwan', dialCode: '+886', phoneDigits: 9 },
  { code: 'TJ', name: 'Tajikistan', dialCode: '+992', phoneDigits: 9 },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255', phoneDigits: 9 },
  { code: 'TH', name: 'Thailand', dialCode: '+66', phoneDigits: 9 },
  { code: 'TL', name: 'Timor-Leste', dialCode: '+670', phoneDigits: 8 },
  { code: 'TG', name: 'Togo', dialCode: '+228', phoneDigits: 8 },
  { code: 'TO', name: 'Tonga', dialCode: '+676', phoneDigits: 5 },
  { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1868', phoneDigits: 7 },
  { code: 'TN', name: 'Tunisia', dialCode: '+216', phoneDigits: 8 },
  { code: 'TR', name: 'Turkey', dialCode: '+90', phoneDigits: 10 },
  { code: 'TM', name: 'Turkmenistan', dialCode: '+993', phoneDigits: 8 },
  { code: 'UG', name: 'Uganda', dialCode: '+256', phoneDigits: 9 },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', phoneDigits: 9 },
  { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', phoneDigits: 9 },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', phoneDigits: 10 },
  { code: 'US', name: 'United States', dialCode: '+1', phoneDigits: 10 },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', phoneDigits: 8 },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', phoneDigits: 9 },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678', phoneDigits: 7 },
  { code: 'VA', name: 'Vatican City', dialCode: '+379', phoneDigits: 10 },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', phoneDigits: 10 },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', phoneDigits: 10 },
  { code: 'YE', name: 'Yemen', dialCode: '+967', phoneDigits: 9 },
  { code: 'ZM', name: 'Zambia', dialCode: '+260', phoneDigits: 9 },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', phoneDigits: 9 },
];

export const useCountryDetection = (): CountryData & { countries: typeof countries } => {
  const [data, setData] = useState<CountryData>({
    country: '',
    countryCode: '',
    isLoading: true,
    error: null,
  });

  useEffect(() => {
    const detectCountry = async () => {
      try {
        // Using a free IP geolocation API
        const response = await fetch('https://ipapi.co/json/');
        if (!response.ok) throw new Error('Failed to detect location');
        
        const result = await response.json();
        const detectedCountry = countries.find(c => c.code === result.country_code);
        
        setData({
          country: detectedCountry?.name || result.country_name || 'United States',
          countryCode: result.country_code || 'US',
          isLoading: false,
          error: null,
        });
      } catch (error) {
        // Default to US if detection fails
        setData({
          country: 'United States',
          countryCode: 'US',
          isLoading: false,
          error: null,
        });
      }
    };

    detectCountry();
  }, []);

  return { ...data, countries };
};
